version: "2.4"

services:
  # A servercore image with both the netcore and netframework SDKs.
  # See Dockerfile for more details.
  dotnetsdk:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-dotnetsdk:${VERSION:-latest}
    build:
      context: ./build/dotnetsdk
      args:
        BUILD_IMAGE: ${SOLUTION_BUILD_IMAGE}
        NETCORE_BUILD_IMAGE: ${NETCORE_BUILD_IMAGE}
    scale: 0

  # The solution build image is added here so it can be referenced as a build dependency
  # for the images which use its output. Setting "scale: 0" means docker-compose will not
  # include it in the running environment. See Dockerfile for more details.
  solution:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-solution:${VERSION:-latest}
    build:
      context: ../
      dockerfile: ./docker/build/solution/Dockerfile
      args:
        BUILD_CONFIGURATION: ${BUILD_CONFIGURATION}
        BASE_IMAGE: ${SOLUTION_BASE_IMAGE}
        BUILD_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}-dotnetsdk:${VERSION:-latest}
    depends_on:
      - dotnetsdk
    scale: 0

  # A Windows-based nodejs base image
  nodejs:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-nodejs:${VERSION:-latest}
    build:
      context: ./build/nodejs-win
      args:
        PARENT_IMAGE: ${NODEJS_PARENT_IMAGE}
        NODEJS_VERSION: ${NODEJS_VERSION}
    scale: 0


  traefik:
    volumes:
      - ./traefik:C:/etc/traefik
    depends_on:
      - cm

  mssql:
    volumes:
      - ${LOCAL_DATA_PATH}\mssql:c:\data
    mem_limit: ${MEM_LIMIT_SQL:-2GB}           
  
  mssql-init:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-mssql-init:${SITECORE_VERSION}
    build:
      context: ./build/mssql-init
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xm1-mssql-init:${SITECORE_VERSION}
        HEADLESS_SERVICES_RESOURCES_IMAGE: ${HEADLESS_SERVICES_RESOURCES_IMAGE}              
        SPE_RESOURCES_IMAGE: ${SPE_RESOURCES_IMAGE}

  solr:
    volumes:            
      - ${LOCAL_DATA_PATH}\solr:c:\data  
    mem_limit: ${MEM_LIMIT_SOLR:-1GB}  

  solr-init:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-solr-init:${SITECORE_VERSION}
    build:
      context: ./build/solr-init
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xm1-solr-init:${SITECORE_VERSION}                
  
  id:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-id6:${SITECORE_VERSION}
    build:
      context: ./build/id
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}${ID_IMAGE}:${SITECORE_VERSION}
    environment:
      SITECORE_LICENSE_LOCATION: c:\license\license.xml
    volumes:
      - ${HOST_LICENSE_FOLDER}:c:\license


  # (OPTIONAL); Uncomment below rendering image to run your jss app in a container.
  #   Set JSS_PROJECT_ROOTFOLDER in .env file with (relative) path to your jss app folder.
  #   Set SITECORE_API_KEY and JSS_EDITING_SECRET, change naming below for other than nextjs
  # rendering:
  #   image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-rendering:${VERSION:-latest}
  #   build:
  #     context: ./build/rendering
  #     args:
  #       PARENT_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}-nodejs:${VERSION:-latest}
  #   volumes:
  #     - ${JSS_PROJECT_ROOTFOLDER}:C:\app
  #   mem_limit: ${MEM_LIMIT_RENDERING:-4GB}
  #   ports:
  #     - 9229:9229  
  #   depends_on:
  #     - cm
  #     - nodejs
  #   environment:
  #     NODE_ENV: ${NODE_ENV}
  #     NEXT_PUBLIC_PUBLIC_URL: "https://${RENDERING_HOST}"
  #     NEXT_PUBLIC_SITECORE_API_KEY: ${SITECORE_API_KEY}
  #     NEXT_PUBLIC_SITECORE_API_HOST: http://cm
  #     JSS_EDITING_SECRET: ${JSS_EDITING_SECRET}
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.rendering-secure.entrypoints=websecure"
  #     - "traefik.http.routers.rendering-secure.rule=Host(`${RENDERING_HOST}`)"
  #     - "traefik.http.routers.rendering-secure.tls=true"      

  cm:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-cm:${SITECORE_VERSION}
    build:
      context: ./build/cm
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}${CM_IMAGE}:${SITECORE_VERSION}
        SOLUTION_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}-solution:${VERSION:-latest}
        TOOLS_RESOURCES_IMAGE: ${TOOLS_RESOURCES_IMAGE}
        DEVEX_RESOURCES_IMAGE: ${DEVEX_RESOURCES_IMAGE}
        SPE_RESOURCES_IMAGE: ${SPE_RESOURCES_IMAGE}
        HEADLESS_SERVICES_RESOURCES_IMAGE: ${HEADLESS_SERVICES_RESOURCES_IMAGE}        
    volumes:
      - ${LOCAL_DEPLOY_PATH}\platform:C:\deploy
      - ${LOCAL_DATA_PATH}\cm:C:\inetpub\wwwroot\App_Data\logs
      - ${HOST_LICENSE_FOLDER}:c:\license
    environment:
      SITECORE_LICENSE_LOCATION: c:\license\license.xml
      SITECORE_DEVELOPMENT_PATCHES: CustomErrorsOff
    depends_on:
      - solution
    mem_limit: ${MEM_LIMIT_CM:-4GB}        
    entrypoint: powershell.exe -Command "& C:\tools\entrypoints\iis\Development.ps1"
